In [48]:
import pandas as pd

In [49]:
orders = pd.read_csv("../datasets/olist_orders_dataset.csv")
payments = pd.read_csv("../datasets/olist_order_payments_dataset.csv")
customers = pd.read_csv("../datasets/olist_customers_dataset.csv")

In [50]:
new_orders = orders.merge(payments, on='order_id')
df_main = new_orders.merge(customers, on='customer_id')

In [52]:
df_main.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,payment_sequential,payment_type,payment_installments,payment_value,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1,credit_card,1,18.12,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,3,voucher,1,2.00,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,2,voucher,1,18.59,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,1,boleto,1,141.46,af07308b275d755c9edb36a90c618231,47813,barreiras,BA
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,1,credit_card,3,179.12,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO

In [53]:
order_value_df = (
    df_main
    .groupby('order_id')['payment_value']
    .sum()
    .reset_index()
)
order_value_df.head()

                           order_id  payment_value
0  00010242fe8c5a6d1ba2dd792cb16214          72.19
1  00018f77f2f0320c557190d7a144bdd3         259.83
2  000229ec398224ef6ca0657da4fc703e         216.87
3  00024acbcdf0a6daa1e931b038114c75          25.78
4  00042b26cf59d7ce69dfabb4e55b4fd9         218.04

In [54]:
order_info = df_main [[
    'order_id',
    'customer_unique_id',
    'order_purchase_timestamp',
    'customer_state'
]].drop_duplicates()
order_info.head()

,order_id,customer_unique_id,order_purchase_timestamp,customer_state
0,e481f51cbdc54678b7cc49136f2d6af7,7c396fd4830fd04220f754e42b4e5bff,2017-10-02 10:56:33,SP
3,53cdb2fc8bc7dce0b6741e2150273451,af07308b275d755c9edb36a90c618231,2018-07-24 20:41:37,BA
4,47770eb9100c2d0c44946d9cf07ec65d,3a653a41f6f9fc3d2a113cf8398680e8,2018-08-08 08:38:49,GO
5,949d5b44dbf5de918fe9c16f97b45f8a,7c142cf63193a1473d2e66489a9ae977,2017-11-18 19:28:06,RN
6,ad21c59c0840e6cb83a9ceb5573f8159,72632f0f9dd73dfee390c9b22eb56dd6,2018-02-13 21:18:39,SP

In [55]:
df_orders = order_info.merge(order_value_df, on="order_id")
df_orders.head()

,order_id,customer_unique_id,order_purchase_timestamp,customer_state,payment_value
0,e481f51cbdc54678b7cc49136f2d6af7,7c396fd4830fd04220f754e42b4e5bff,2017-10-02 10:56:33,SP,38.71
1,53cdb2fc8bc7dce0b6741e2150273451,af07308b275d755c9edb36a90c618231,2018-07-24 20:41:37,BA,141.46
2,47770eb9100c2d0c44946d9cf07ec65d,3a653a41f6f9fc3d2a113cf8398680e8,2018-08-08 08:38:49,GO,179.12
3,949d5b44dbf5de918fe9c16f97b45f8a,7c142cf63193a1473d2e66489a9ae977,2017-11-18 19:28:06,RN,72.20
4,ad21c59c0840e6cb83a9ceb5573f8159,72632f0f9dd73dfee390c9b22eb56dd6,2018-02-13 21:18:39,SP,28.62

*Top Paying Customers*

In [57]:
top_customers = (
    df_orders
    .groupby('customer_unique_id')['payment_value']
    .sum()
    .reset_index()
    .sort_values(by='payment_value', ascending=False)
)
top_customers

                     customer_unique_id  payment_value
3826   0a0a92112bd4c708ca5fde585afaa872       13664.08
26456  46450c74a0d8c5ca9395da1daac6c120        9553.02
81961  da122df9eeddfedc1dc1f5349a1a690c        7571.63
44447  763c8b1c9c68a0229c42c9fc6f662b93        7274.88
82807  dc4802a71eae9be1dd28f5d788ceb526        6929.31
...                                 ...            ...
67387  b33336f46234b24a613ad9064d13106d          10.89
71051  bd06ce0e06ad77a7f681f1a4960a3cc6          10.07
18643  317cfc692e3f86c45c95697c61c853a6           9.59
29977  4fa4365000c7090fcb8cad5713c6d3db           0.00
56518  968fac81e2c44fb6c1e3ac2a45e6a102           0.00

[96095 rows x 2 columns]

*Revenue By State*

In [58]:
revenue_by_state = (
    df_orders
    .groupby('customer_state')['payment_value']
    .sum()
    .reset_index()
    .sort_values(by='payment_value', ascending=False)
)
revenue_by_state.head()

   customer_state  payment_value
25             SP     5998226.96
18             RJ     2144379.69
10             MG     1872257.26
22             RS      890898.54
17             PR      811156.38

*Number Of Orders Per Month*

In [59]:
df_orders['order_purchase_timestamp'] = pd.to_datetime(df_orders['order_purchase_timestamp'])
df_orders["order_month"] = df_orders["order_purchase_timestamp"].dt.to_period("M")

In [60]:
orders_per_month = (
    df_orders
    .groupby('order_month')['order_id']
    .count()
    .reset_index()
)
orders_per_month.head()

  order_month  order_id
0     2016-09         3
1     2016-10       324
2     2016-12         1
3     2017-01       800
4     2017-02      1780

In [61]:
# df_orders = df_orders.sort_values(['customer_unique_id', 'order_purchase_timestamp'])
# df_orders['prev_value'] = (
#     df_orders
#     .groupby('customer_unique_id')['payment_value']
#     .shift(1)
# )
# df_orders['is_increasing'] = (
#     (df_orders['payment_value'] > df_orders['prev_value']) |
#     (df_orders['prev_value'].isna())
# )
# order_count = (
#     df_orders
#     .groupby('customer_unique_id')['order_id']
#     .count()
#     .reset_index()
# )
# multiple_orders = order_count[order_count['order_id'] > 1]
# df_filtered = df_orders[
#     df_orders['customer_unique_id'].isin(multiple_orders['customer_unique_id'])
# ]
# result = (
#     df_orders
#     .groupby('customer_unique_id')['is_increasing']
#     .all()
#     .reset_index()
# )
# increasing_customers = result[result['is_increasing'] == True]

In [62]:
# increasing_customers

In [63]:
df_orders = df_orders.sort_values(["customer_unique_id", "order_purchase_timestamp"])

df_orders["prev_value"] = df_orders.groupby("customer_unique_id")["payment_value"].shift(1)

df_orders[df_orders["payment_value"] > df_orders["prev_value"]]

,order_id,customer_unique_id,order_purchase_timestamp,customer_state,payment_value,order_month,prev_value
41096,81a93b2fa39e104b865b2bc471c16008,0058f300f57d7b93c477a131a59b36c3,2018-03-22 18:09:41,BA,96.02,2018-03,79.56
84190,d61b915b69851aec8a8865f36cfd793e,00cc12a6d8b578b8ebd21ea4e2ae8b27,2017-03-21 19:25:23,SP,81.78,2017-03,44.42
12466,93b35affb86435b71ca01a6dd1eab2b1,011b4adcd54683b480c4d841250a987f,2018-02-15 11:40:57,BA,149.88,2018-02,86.42
12329,e49d0607832db7c3b1343764225d8df6,012452d40dafae4df401bced74cdb490,2018-05-14 12:12:45,SP,340.07,2018-05,155.26
46105,207258d556f9b9784b54de837ae49286,012a218df8995d3ec3bb221828360c86,2018-06-18 13:08:38,SP,1435.97,2018-06,74.41
...,...,...,...,...,...,...,...
62949,3e677665a6566b610e6f1344ade7b146,fe613188d4d20ea3e3dc1290549c3ad1,2017-11-20 12:47:30,SP,134.45,2017-11,61.75
81217,556b30ae47829a82927b5dff9ca2ba65,fe81bb32c243a86b2f86fbf053fe6140,2018-02-23 14:34:34,SP,78.88,2018-02,63.78
4176,882af1e2ad3e4b132d4b23c429843dc8,fe81bb32c243a86b2f86fbf053fe6140,2018-06-14 11:35:32,SP,1035.79,2018-06,78.88
39588,02b0bf9164ac7753f9880e46dba17f6c,fed2005ccab4fcf1a40ebdaff032a148,2017-06-17 17:04:31,SP,63.42,2017-06,37.68
35244,5f79e2da24a52e76bc22897df03a7901,ff922bdd6bafcdf99cb90d7f39cea5b3,2017-08-23 13:15:29,SP,57.60,2017-08,39.42